#!/bin/sh

ROOT_DIR=${SAVITAR_MONITOR_ROOT}/monitor
cd ${ROOT_DIR}

if [ -f CMakeLists.txt ]
then
    mkdir -p build 
    cd build 
    cmake ..
    make $*
else
    echo "CMakeLists.txt isn't existed!"
    exit 0
fi

